import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/assets/styles/globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="container" style={{ padding: '16px 0' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <div style={{ width: 28, height: 28, borderRadius: 6, background: '#f3f4f6' }} />
              <div style={{ fontWeight: 700 }}>Grid & Circle</div>
            </div>
            <nav style={{ display: 'flex', gap: 16, color: '#6b7280', fontSize: 14 }}>
              <a>상품목록</a>
              <a>주문조회</a>
            </nav>
            <div style={{ width: 28, height: 28, borderRadius: 6, background: '#f3f4f6' }} />
          </div>
        </header>
        <main className="container" style={{ paddingBottom: 32 }}>
          {children}
        </main>
      </body>
    </html>
  );
}
